/**
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  userDocsSidebar: [
    {
      type: 'category',
      collapsed: false,
      label: '🚀 Getting Started',
      items: [
        {
          type: 'doc',
          id: 'user-docs/intro',
          label: 'Welcome!',
        },
        {
          type: 'doc',
          id: 'user-docs/prerequisites',
          label: 'Prerequisites',
        },
        {
          type: 'doc',
          id: 'user-docs/quick-start-guide',
          label: 'Quick Start Guide',
        },
        {
          type: 'doc',
          id: 'user-docs/dashboard-navigation',
          label: 'Navigating the Dashboard',
        },
      ],
    },
    {
      type: 'category',
      collapsed: true,
      label: '🌍 Introduction to AquaBera',
      items: [
        {
          type: 'doc',
          id: 'user-docs/aquabera-overview',
          label: 'Overview of AquaBera',
        },
        {
          type: 'doc',
          id: 'user-docs/what-is-aquabera',
          label: 'What is AquaBera?',
        },
        {
          type: 'doc',
          id: 'user-docs/features-benefits',
          label: 'Key Features and Benefits',
        },
        {
          type: 'doc',
          id: 'user-docs/relationship-kodiak-berachain',
          label: 'Relationship with Kodiak and BeraChain',
        },
        {
          type: 'doc',
          id: 'user-docs/why-aquabera',
          label: 'Why Use AquaBera?',
        },
      ],
    },
    {
      type: 'category',
      collapsed: true,
      label: '🛡️ Understanding BeraChain’s Proof-of-Liquidity (PoL)',
      items: [
        {
          type: 'doc',
          id: 'user-docs/intro-pol',
          label: 'Introduction to PoL',
        },
        {
          type: 'doc',
          id: 'user-docs/what-is-pol',
          label: 'What is Proof-of-Liquidity?',
        },
        {
          type: 'doc',
          id: 'user-docs/pol-mechanics',
          label: 'How PoL Works on BeraChain',
        },
        {
          type: 'doc',
          id: 'user-docs/pol-importance',
          label: 'Importance of PoL',
        },
        {
          type: 'category',
          label: '👥 Key Participants in PoL',
          items: [
            {
              type: 'doc',
              id: 'user-docs/pol-validators',
              label: 'Validators',
            },
            {
              type: 'doc',
              id: 'user-docs/pol-bgt-holders-farmers',
              label: '$BGT Holders & Farmers',
            },
            {
              type: 'doc',
              id: 'user-docs/pol-bera-foundation',
              label: 'Bera Foundation',
            },
            {
              type: 'doc',
              id: 'user-docs/pol-ecosystem-projects',
              label: 'Ecosystem Projects',
            },
          ],
        },
        {
          type: 'doc',
          id: 'user-docs/gauges-roles',
          label: 'Gauges and Their Roles',
        },
        {
          type: 'doc',
          id: 'user-docs/incentives-pol',
          label: 'Incentives in PoL',
        },
      ],
    },
    {
      type: 'category',
      collapsed: true,
      label: '🌐 Liquidity Management on Kodiak via AquaBera',
      items: [
        {
          type: 'doc',
          id: 'user-docs/intro-kodiak',
          label: 'Introduction to Kodiak',
        },
        {
          type: 'doc',
          id: 'user-docs/kodiak-amm-overview',
          label: 'Kodiak AMM Model Overview',
        },
        {
          type: 'doc',
          id: 'user-docs/kodiak-concepts',
          label: 'Key Concepts: Liquidity, Islands',
        },
        {
          type: 'doc',
          id: 'user-docs/manage-liquidity-pools',
          label: 'Creating and Managing Liquidity Pools',
        },
        {
          type: 'doc',
          id: 'user-docs/liquidity-strategies',
          label: 'Liquidity Provision Strategies',
        },
        {
          type: 'doc',
          id: 'user-docs/unique-features',
          label: 'Unique Features of AquaBera',
        },
      ],
    },
    {
      type: 'category',
      collapsed: true,
      label: '🗳️ Gauges and Voting Mechanisms',
      items: [
        {
          type: 'doc',
          id: 'user-docs/gauges-overview',
          label: 'Understanding Gauges',
        },
        {
          type: 'doc',
          id: 'user-docs/gauge-voting',
          label: 'Voting on Gauges',
        },
      ],
    },
    {
      type: 'category',
      collapsed: true,
      label: '🎁 Incentives and Rewards',
      items: [
        {
          type: 'doc',
          id: 'user-docs/incentives-overview',
          label: 'Overview of Incentives',
        },
        {
          type: 'doc',
          id: 'user-docs/rewards-management',
          label: 'Maximizing Rewards with AquaBera',
        },
      ],
    },
  ],

  communitySidebar: [
    {
      type: 'doc',
      id: 'community/intro',
      label: 'Introduction to Community',
    },
    {
      type: 'category',
      collapsed: false,
      label: '💧 Tokenomics',
      items: [
        {
          type: 'doc',
          id: 'community/tokenomics/tokenomics',
          label: 'AquaBera Tokenomics Story',
        },
        {
          type: 'doc',
          id: 'community/tokenomics/tokenomics-tldr',
          label: 'TL;DR of AquaBera Tokenomics',
        },
        {
          type: 'doc',
          id: 'community/tokenomics/aquabera-model',
          label: 'The AquaBera Tokenomics Model',
        },
        {
          type: 'doc',
          id: 'community/tokenomics/benefits-and-implications',
          label: 'Benefits and Implications',
        },
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: '🤝 Partners',
      items: [
        {
          type: 'doc',
          id: 'community/partners/amplifi',
          label: 'Amplifi',
        },
        {
          type: 'doc',
          id: 'community/partners/aegis',
          label: 'Aegis',
        },
      ],
    },
  ],

};

module.exports = sidebars;